### ISSUE TITLE
Hard to find this repository...

### ISSUE THREAD

**Issue by auspex** [mishunov/webcouturier.dropdownmenu#2]
Please update at least one of pypi or http://plone.org/products/webcouturier-dropdownmenu/ to point to this repository.  It's far from intuitive to find that I have to go up the tree (ie, "trunk" isn't even found now) and read the readme.txt

And if you've got the time, I'd love to know how you managed to move dropdownmenu here - I've been trying for ages to move my own repo...

**Comment by hannosch** [comment]
On Wed, May 25, 2011 at 9:01 PM, auspex
reply@reply.github.com
wrote:

> And if you've got the time, I'd love to know how you managed to move dropdownmenu here - I've been trying for ages to move my own repo...

For migrating from Subversion to Git I found those two blog posts quite helpful:

http://blog.johngoulah.com/2009/11/migrating-svn-to-git/
http://blog.woobling.org/2009/06/git-svn-abandon.html

If your code is in the collective, you cannot use the simple Github
web interface to do an import. The collective is just way too big for
that to work.

Hanno

## 

Hanno C. Schlichting
www.jarn.com/hanno

**Comment by auspex** [comment]
On Wed, May 25, 2011 at 5:39 PM, hannosch <
reply@reply.github.com>wrote:

> If your code is in the collective, you cannot use the simple Github
> web interface to do an import. The collective is just way too big for
> that to work.

Yeah - but I couldn't manage to get the manual method specified on github to
work either.  The fact that you (or someone) got dropdownmenu moved is
encouraging :-)  Thanks

## 

derek

**Comment by mishunov** [comment]
On Wed, May 25, 2011 at 9:01 PM, auspex reply@reply.github.com wrote:

> Please update at least one of pypi or http://plone.org/products/webcouturier-dropdownmenu/ to point to this repository. It's far from intuitive to find that I have to go up the tree (ie, "trunk" isn't even found now) and read the readme.txt

I have updated the main links on pypi and plone.org to point to the git repository. I think having nothing on previous location (plone collective svn) is better than having some readme.txt — buildout will immediately yell and let know that the package is not found. After this, developers usually go to pypi and check the development URLs and update their buildouts. If there is something like readme.txt on the old place, buildout will silently download it and developers will spend time figuring out why the package is not available. So, I consider the issue being closed.

**Comment by auspex** [comment]
Thanks - yes I think having nothing at the old location is good.
