### ISSUE TITLE
IE 9 Compatibility ?

### ISSUE THREAD

**Issue by senner** [mishunov/webcouturier.dropdownmenu#6]
IE9 doesn't seem to be able to work correctly.

Mouse hover doesn't pop out the menu. But if you load the page with the mouse already hovering on a top level the menu will popout, but on mouse out, the menu doesn't release.

http://www.wildcardcorp.com/

IE8 works fine.

**Comment by mishunov** [comment]
I am working on the new release of the package and will keep in mind IE9 testing. Will make sure things work properly there in the final release. Don't have an opportunity to check IE9 with the existing release atm though.

**Comment by senner** [comment]
Let me know if there's anything I can test. I have a windows machine that
I've been using the "ietester" program in.
On Aug 14, 2011 1:18 AM, "mishunov" <
reply@reply.github.com>
wrote:

**Comment by toutpt** [comment]
Issue reported on new repository (collective). Fixed as shown in http://www.screenr.com/P5as
